%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%功能：求解伴生网格信息
%输入：伴生网格信息，重心列表，节点信息列表
%返回：伴生网格信息列表：第一列为长度，第二三列为对应面积，第四五列为法向量坐标
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [fluxfaceList1]=fluxface(fluxfaceList,barycenter ,nodeList )
[Nfluxface,~]=size(fluxfaceList);
fluxfaceList1=zeros(Nfluxface,5);%第一列为长度，第二三列为对应面积，第四五列为法向量坐标
%求长度
fluxfaceList1(:,1)=sqrt( ( barycenter(fluxfaceList(:,1),1)-barycenter(fluxfaceList(:,2),1) ).^2 +...
                                 ( barycenter(fluxfaceList(:,1),2)-barycenter(fluxfaceList(:,2),2) ).^2 );
%求面积   (一个fulxface，包括两个)
fluxfaceList1(:,2)=abs(   (  ( nodeList( fluxfaceList(:,3) ,2)+ nodeList( fluxfaceList(:,4) ,2))/2-barycenter(fluxfaceList(:,1),1) )...
    .*(   nodeList( fluxfaceList(:,3) ,3) -  barycenter(fluxfaceList(:,1),2)   )-(  nodeList( fluxfaceList(:,3) ,2) -  barycenter(fluxfaceList(:,1),1)  )...
    .* (  ( nodeList( fluxfaceList(:,3) ,3)+ nodeList( fluxfaceList(:,4) ,3))/2-barycenter(fluxfaceList(:,1),2) )  )/2+...
   abs(     (  ( nodeList( fluxfaceList(:,3) ,2)+ nodeList( fluxfaceList(:,4) ,2))/2-barycenter(fluxfaceList(:,2),1) )  ...
    .*(   nodeList( fluxfaceList(:,3) ,3) -  barycenter(fluxfaceList(:,2),2)   )-(  nodeList( fluxfaceList(:,3) ,2) -  barycenter(fluxfaceList(:,2),1)  )...
    .* (  ( nodeList( fluxfaceList(:,3) ,3)+ nodeList( fluxfaceList(:,4) ,3))/2-barycenter(fluxfaceList(:,2),2) )    )/2;
fluxfaceList1(:,3)=abs(     (  ( nodeList( fluxfaceList(:,3) ,2)+ nodeList( fluxfaceList(:,4) ,2))/2-barycenter(fluxfaceList(:,1),1) )...
    .*(   nodeList( fluxfaceList(:,4) ,3) -  barycenter(fluxfaceList(:,1),2)   )-(  nodeList( fluxfaceList(:,4) ,2) -  barycenter(fluxfaceList(:,1),1)  )...
    .* (  ( nodeList( fluxfaceList(:,3) ,3)+ nodeList( fluxfaceList(:,4) ,3))/2-barycenter(fluxfaceList(:,1),2) )   )/2+...
   abs(    (  ( nodeList( fluxfaceList(:,3) ,2)+ nodeList( fluxfaceList(:,4) ,2))/2-barycenter(fluxfaceList(:,2),1) )...
    .*(   nodeList( fluxfaceList(:,4) ,3) -  barycenter(fluxfaceList(:,2),2)   )-(  nodeList( fluxfaceList(:,4) ,2) -  barycenter(fluxfaceList(:,2),1)  )...
    .* (  ( nodeList( fluxfaceList(:,3) ,3)+ nodeList( fluxfaceList(:,4) ,3))/2-barycenter(fluxfaceList(:,2),2) )    )/2;
%求法向量坐标   ( 方向指向list_int列表的第3列  )
x=barycenter(fluxfaceList(:,1),1)-barycenter(fluxfaceList(:,2),1);
y=barycenter(fluxfaceList(:,1),2)-barycenter(fluxfaceList(:,2),2);
vector(:,1)=nodeList( fluxfaceList(:,3) ,2)- nodeList( fluxfaceList(:,4) ,2);
vector(:,2)=nodeList( fluxfaceList(:,3) ,3)- nodeList( fluxfaceList(:,4) ,3);
 [n]=normalVector(x,y,vector);
 fluxfaceList1(:,4:5)=n;